### PR TITLE
refactor: optimize google fonts

### PR DESCRIPTION
**Pull request by alanlisler**
## Related Issue

https://vsf.atlassian.net/browse/M2-292

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by Frodigo — APPROVED** [review]

**Comment by Frodigo** [comment]
@alanlisler please resolve conflicts, thanks!

**Comment by sethidden** [comment]
@alanlisler Hey, I noticed you removed the nuxtjs/google-fonts module and used a community-made one. Did the official module's "download" property not work? https://google-fonts.nuxtjs.org/downloading#download

**Review by sethidden — CHANGES_REQUESTED** [review]
@alanlisler Hey, I noticed you removed the nuxtjs/google-fonts module and used a community-made one. Did the official module's "download" property not work? https://google-fonts.nuxtjs.org/downloading#download

**Review by sethidden — APPROVED** [review]
Spoke with Marcin - it's ok

**Pull request merged**
