### PR TITLE
fix: header navigation "hasChildren" always returning true

### PR DESCRIPTION
**Pull request by bensinca**
## Description
If the value passed to Boolean is an empty array it will always return true.

## Related Issue
https://github.com/vuestorefront/magento2/issues/1207

## Types of changes

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by bartoszherba** [comment]
@bensinca Could you fix your branch?

**Comment by bensinca** [comment]
@bartoszherba done!

**Comment by bartoszherba** [comment]
@bensinca What do you mean? You must rebase your branch, it looks like it includes A LOT of unrelated changes.

**Comment by bartoszherba** [comment]
@bensinca any chances to rebase your branch?

**Comment by bensinca** [comment]
@bartoszherba I don't have access to a laptop so I am doing this from my tablet. As I don't have access to a CLI I will just create a new fork/PL. https://github.com/vuestorefront/magento2/pull/1315

**Pull request closed without merging**
