### PR TITLE
build: disabled nuxt modern mode

### PR DESCRIPTION
**Pull request by Frodigo**
## Description
disabled nuxt modern mode

## Motivation and Context
Nuxt modern mode is blocking CDN/Redis support for the integration.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by sethidden — CHANGES_REQUESTED** [review]
I don't really understand the consequences of this change - how do the modern mode's modules affect CDNs? I asked Wojtek in https://github.com/vuestorefront/bigcommerce/pull/380

**Comment by Frodigo** [comment]
> I don't really understand the consequences of this change - how do the modern mode's modules affect CDNs? I asked Wojtek in [vuestorefront/bigcommerce#380](https://github.com/vuestorefront/bigcommerce/pull/380) aswell

@sethidden basically, Nuxt generates two builds: client and modern, and based on browser, a correct version of the build is chosen when a user enters a page. 

So if you enter to page, that page will be cached in CDN/Redis and then if someone else enters the page, the cache system will render the cached website for a different browser. 

On the other hand, our build config for the client mode and for the modern mode are the same.

**Comment by sethidden** [comment]
I spoke with Wojtek on the bigcommerce equivalent of this PR - let's see if --modern="client" works there first

**Review by bartoszherba — APPROVED** [review]

**Review by bartoszherba — APPROVED** [review]

**Comment by sethidden** [comment]
@Frodigo Can you align this with what was merged in https://github.com/vuestorefront/bigcommerce/pull/380#issuecomment-1075260725 ?

**Review by sethidden — APPROVED** [review]

**Comment by Frodigo** [comment]
@sethidden I aligned this PR to a new approach. Please re-review.

**Pull request merged**
