### PR TITLE
docs: added documentation for creating a store

### PR DESCRIPTION
**Pull request by themarcba**
Replaced the documentation for creating a store 

## Description
Replaced the documentation for creating a store with a more current and detailed version, including a full local setup of the Magento server, and maneuvering around some pitfalls and errors occurring in the frontend.

## Motivation and Context

Setting up a Magento server bears its challenges. Also, the current version of the integration is in development and lacking documentation for this.

## How Has This Been Tested?
I retraced the documentation points step-by-step with a whole new instance.

## Screenshots (if appropriate):
None

## Types of changes

- [x] Documentation change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Frodigo** [comment]
After a conversation with @filipsobol, I converted this one to draft for now.

**Comment by Frodigo** [comment]
@filipsobol do you plan to finish this one soon?

**Comment by filipsobol** [comment]
@Frodigo Yes, after we finish docs for composables, which have higher priority

**Comment by Frodigo** [comment]
@filipsobol do you plan to continue work on it? If not, please close this one.

**Pull request closed without merging**
