### PR TITLE
refactor(theme): update components to Storefront-UI 0.12.1

### PR DESCRIPTION
**Pull request by bloodf**
## Description
update the components to use SfImage and the new Storefront-UI 0.12.1

## Related Issue
N/A
## How Has This Been Tested?
Locally tested

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by bartoszherba — DISMISSED** [review]

**Comment by Frodigo** [comment]
There is a bug in storefront-ui that blocks me from merging this PR: https://github.com/vuestorefront/storefront-ui/issues/2277

**Comment by sethidden** [comment]
Marcin requested my review but given that there are workshops underway I guess it's best to wait till Tuesday at least

**Comment by bartoszherba** [comment]
@bloodf 
Hi, I can see that there is a LOT of changes that are not related to the StorefrontUI update and I do not even know how to review this PR. For example, how I can test this PR?  There are build changes, gitflow changes, images changes, some new lazy load components. Could you please split this into testable and meaningful PR so we can validate it and the tester will have clear instruction on how to test them?

**Review by bartoszherba — CHANGES_REQUESTED** [review]
@bloodf
Hi, I can see that there is a LOT of changes that are not related to the StorefrontUI update and I do not even know how to review this PR. For example, how I can test this PR? There are build changes, gitflow changes, images changes, some new lazy load components. Could you please split this into testable and meaningful PR so we can validate it and the tester will have clear instruction on how to test them?

**Comment by bloodf** [comment]
> @bloodf Hi, I can see that there is a LOT of changes that are not related to the StorefrontUI update and I do not even know how to review this PR. For example, how I can test this PR? There are build changes, gitflow changes, images changes, some new lazy load components. Could you please split this into testable and meaningful PR so we can validate it and the tester will have clear instruction on how to test them?

I will create a new PR with the SFUI and other with the updates :)

Sorry for the confusion

**Comment by sethidden** [comment]
After this is merged it would make sense to start upgrading to 0.12.2 on our team's side, as there's an important change https://github.com/vuestorefront/storefront-ui/pull/2266 for perf there

**Pull request closed without merging**
